# Generated by Django 5.2.4 on 2025-07-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('not_started', 'Not started'), ('completed', 'Completed')], default='not_started', max_length=12),
        ),
    ]
