# Generated by Django 5.2.4 on 2025-07-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='not_started', max_length=12),
        ),
    ]
