# Generated by Django 5.2.4 on 2025-07-12 15:17

from django.db import migrations
from django.contrib.auth import get_user_model

def set_user_for_existing_tasks(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    User = get_user_model()
    default_user = User.objects.first()  # Use the first user as default
    if default_user:
        for task in Task.objects.filter(user__isnull=True):
            task.user = default_user
            task.save()
    # If no user exists, leave as null (should be fixed before making non-nullable)

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_user'),
    ]

    operations = [
        migrations.RunPython(set_user_for_existing_tasks),
    ]
