# Generated by Django 5.2.4 on 2025-07-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_user_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tasklist'),
        ),
    ]
