# Generated by Django 5.2.4 on 2025-07-13 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_tasklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_tasklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
